/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation; either version
 * 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 */

package com.yxxs.model.impl;

import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringPool;

import com.yxxs.common.service.BaseModelImpl;

import com.yxxs.model.GroupEntity;
import com.yxxs.model.GroupEntityModel;

import org.codehaus.jackson.annotate.JsonIgnore;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;

/**
 * The base model implementation for the GroupEntity service. Represents a row in the
 * &quot;yxxs_sec_group&quot; database table, with each column mapped to a property of this class.
 * 
 * <p>
 * This implementation and its corresponding interface {@link com.yxxs.model.GroupEntityModel} exist
 * only as a container for the default property accessors generated by ServiceBuilder. Helper
 * methods and all application logic should be put in {@link GroupEntityImpl}.
 * </p>
 * 
 * @author Administrator
 * @see GroupEntityImpl
 * @see com.yxxs.model.GroupEntity
 * @see com.yxxs.model.GroupEntityModel
 * @generated
 */
@JSON(strict = true)
public class GroupEntityModelImpl extends BaseModelImpl<GroupEntity> implements GroupEntityModel {
  /*
   * NOTE FOR DEVELOPERS:
   * 
   * Never modify or reference this class directly. All methods that expect a group entity model
   * instance should use the {@link com.yxxs.model.GroupEntity} interface instead.
   */
  public static final String TABLE_NAME = "yxxs_sec_group";
  public static final Object[][] TABLE_COLUMNS = { {"id_", Types.BIGINT}, {"title", Types.VARCHAR},
      {"code_", Types.VARCHAR}, {"description", Types.VARCHAR}, {"status", Types.VARCHAR}};
  public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
      com.yxxs.common.util.BaseServicePropsUtil
          .get("value.object.entity.cache.enabled.com.yxxs.model.GroupEntity"), true);
  public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
      com.yxxs.common.util.BaseServicePropsUtil
          .get("value.object.finder.cache.enabled.com.yxxs.model.GroupEntity"), true);
  public static final boolean COLUMN_BITMASK_ENABLED = false;

  public GroupEntityModelImpl() {}

  public long getPrimaryKey() {
    return _id_;
  }

  public void setPrimaryKey(long primaryKey) {
    setId(primaryKey);
  }

  @JsonIgnore
  public Serializable getPrimaryKeyObj() {
    return new Long(_id_);
  }

  public void setPrimaryKeyObj(Serializable primaryKeyObj) {
    setPrimaryKey(((Long) primaryKeyObj).longValue());
  }

  @JsonIgnore
  public Class<?> getModelClass() {
    return GroupEntity.class;
  }

  @JsonIgnore
  public String getModelClassName() {
    return GroupEntity.class.getName();
  }

  @JSON
  public long getId() {
    return _id_;
  }

  public void setId(long id) {
    this._id_ = id;
  }

  @JSON
  public String getTitle() {
    if (_title == null) {
      return StringPool.BLANK;
    } else {
      return _title;
    }
  }

  public void setTitle(String title) {
    this._title = title;
  }

  @JSON
  public String getCode() {
    if (_code_ == null) {
      return StringPool.BLANK;
    } else {
      return _code_;
    }
  }

  public void setCode(String code) {
    this._code_ = code;
  }

  @JSON
  public String getDescription() {
    if (_description == null) {
      return StringPool.BLANK;
    } else {
      return _description;
    }
  }

  public void setDescription(String description) {
    this._description = description;
  }

  @JSON
  public String getStatus() {
    if (_status == null) {
      return StringPool.BLANK;
    } else {
      return _status;
    }
  }

  public void setStatus(String status) {
    this._status = status;
  }

  @Override
  public GroupEntity toEscapedModel() {
    return null;
  }

  @Override
  public Object clone() {
    GroupEntityImpl groupEntityImpl = new GroupEntityImpl();

    groupEntityImpl.setId(getId());
    groupEntityImpl.setTitle(getTitle());
    groupEntityImpl.setCode(getCode());
    groupEntityImpl.setDescription(getDescription());
    groupEntityImpl.setStatus(getStatus());

    groupEntityImpl.resetOriginalValues();

    return groupEntityImpl;
  }

  public int compareTo(GroupEntity groupEntity) {
    long primaryKey = groupEntity.getPrimaryKey();

    if (getPrimaryKey() < primaryKey) {
      return -1;
    } else if (getPrimaryKey() > primaryKey) {
      return 1;
    } else {
      return 0;
    }
  }

  @Override
  public boolean equals(Object obj) {
    if (obj == null) {
      return false;
    }

    GroupEntity groupEntity = null;

    try {
      groupEntity = (GroupEntity) obj;
    } catch (ClassCastException cce) {
      return false;
    }

    long primaryKey = groupEntity.getPrimaryKey();

    if (getPrimaryKey() == primaryKey) {
      return true;
    } else {
      return false;
    }
  }

  @Override
  public int hashCode() {
    return (int) getPrimaryKey();
  }

  @Override
  public void resetOriginalValues() {}

  public HashMap toHash() {
    HashMap hash = new HashMap();

    hash.put("id", getId());
    hash.put("title", getTitle());
    hash.put("code", getCode());
    hash.put("description", getDescription());
    hash.put("status", getStatus());

    return hash;
  }

  private long _id_;
  private String _title;
  private String _code_;
  private String _description;
  private String _status;
}
