/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.model.impl;

import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringPool;

import com.yxxs.common.service.BaseModelImpl;

import com.yxxs.model.YxxsActionUser;
import com.yxxs.model.YxxsActionUserModel;

import org.codehaus.jackson.annotate.JsonIgnore;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;

/**
 * The base model implementation for the YxxsActionUser service. Represents a row in the &quot;yxxs_action_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.yxxs.model.YxxsActionUserModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YxxsActionUserImpl}.
 * </p>
 *
 * @author Administrator
 * @see YxxsActionUserImpl
 * @see com.yxxs.model.YxxsActionUser
 * @see com.yxxs.model.YxxsActionUserModel
 * @generated
 */
@JSON(strict = true)
public class YxxsActionUserModelImpl extends BaseModelImpl<YxxsActionUser>
	implements YxxsActionUserModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a yxxs action user model instance should use the {@link com.yxxs.model.YxxsActionUser} interface instead.
	 */
	public static final String TABLE_NAME = "yxxs_action_user";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "actionId", Types.BIGINT },
			{ "createId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "userType", Types.INTEGER },
			{ "isLogged", Types.INTEGER },
			{ "openId", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "loginDate", Types.TIMESTAMP },
			{ "rName", Types.VARCHAR },
			{ "rMobile", Types.VARCHAR },
			{ "rSchool", Types.VARCHAR }
		};
	public static final String ORDER_BY_JPQL = " ORDER BY yxxsActionUser.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY yxxs_action_user.createDate DESC";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.entity.cache.enabled.com.yxxs.model.YxxsActionUser"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.finder.cache.enabled.com.yxxs.model.YxxsActionUser"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.column.bitmask.enabled.com.yxxs.model.YxxsActionUser"),
			true);
	public static long ACTIONID_COLUMN_BITMASK = 1L;
	public static long OPENID_COLUMN_BITMASK = 2L;
	public static long USERID_COLUMN_BITMASK = 4L;

	public YxxsActionUserModelImpl() {
	}

	public long getPrimaryKey() {
		return _id_;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@JsonIgnore
	public Serializable getPrimaryKeyObj() {
		return new Long(_id_);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@JsonIgnore
	public Class<?> getModelClass() {
		return YxxsActionUser.class;
	}

	@JsonIgnore
	public String getModelClassName() {
		return YxxsActionUser.class.getName();
	}

	@JSON
	public long getId() {
		return _id_;
	}

	public void setId(long id) {
		this._id_ = id;
	}

	@JSON
	public long getActionId() {
		return _actionId;
	}

	public void setActionId(long actionId) {
		if (!_setOriginalActionId) {
			_setOriginalActionId = true;

			_originalActionId = _actionId;
		}

		this._actionId = actionId;
	}

	@JsonIgnore
	public long getOriginalActionId() {
		return _originalActionId;
	}

	@JSON
	public long getCreateId() {
		return _createId;
	}

	public void setCreateId(long createId) {
		this._createId = createId;
	}

	@JSON
	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		this._userId = userId;
	}

	@JsonIgnore
	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	public int getUserType() {
		return _userType;
	}

	public void setUserType(int userType) {
		this._userType = userType;
	}

	@JSON
	public int getIsLogged() {
		return _isLogged;
	}

	public void setIsLogged(int isLogged) {
		this._isLogged = isLogged;
	}

	@JSON
	public String getOpenId() {
		if (_openId == null) {
			return StringPool.BLANK;
		}
		else {
			return _openId;
		}
	}

	public void setOpenId(String openId) {
		if (_originalOpenId == null) {
			_originalOpenId = _openId;
		}

		this._openId = openId;
	}

	@JsonIgnore
	public String getOriginalOpenId() {
		return GetterUtil.getString(_originalOpenId);
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		this._createDate = createDate;
	}

	@JSON
	public Date getLoginDate() {
		return _loginDate;
	}

	public void setLoginDate(Date loginDate) {
		this._loginDate = loginDate;
	}

	@JSON
	public String getRName() {
		if (_rName == null) {
			return StringPool.BLANK;
		}
		else {
			return _rName;
		}
	}

	public void setRName(String rName) {
		this._rName = rName;
	}

	@JSON
	public String getRMobile() {
		if (_rMobile == null) {
			return StringPool.BLANK;
		}
		else {
			return _rMobile;
		}
	}

	public void setRMobile(String rMobile) {
		this._rMobile = rMobile;
	}

	@JSON
	public String getRSchool() {
		if (_rSchool == null) {
			return StringPool.BLANK;
		}
		else {
			return _rSchool;
		}
	}

	public void setRSchool(String rSchool) {
		this._rSchool = rSchool;
	}

	@JsonIgnore
	public long getColumnBitmask() {
		return 0L;
	}

	@Override
	public YxxsActionUser toEscapedModel() {
		return null;
	}

	@Override
	public Object clone() {
		YxxsActionUserImpl yxxsActionUserImpl = new YxxsActionUserImpl();

		yxxsActionUserImpl.setId(getId());
		yxxsActionUserImpl.setActionId(getActionId());
		yxxsActionUserImpl.setCreateId(getCreateId());
		yxxsActionUserImpl.setUserId(getUserId());
		yxxsActionUserImpl.setUserType(getUserType());
		yxxsActionUserImpl.setIsLogged(getIsLogged());
		yxxsActionUserImpl.setOpenId(getOpenId());
		yxxsActionUserImpl.setCreateDate(getCreateDate());
		yxxsActionUserImpl.setLoginDate(getLoginDate());
		yxxsActionUserImpl.setRName(getRName());
		yxxsActionUserImpl.setRMobile(getRMobile());
		yxxsActionUserImpl.setRSchool(getRSchool());

		yxxsActionUserImpl.resetOriginalValues();

		return yxxsActionUserImpl;
	}

	public int compareTo(YxxsActionUser yxxsActionUser) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				yxxsActionUser.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		YxxsActionUser yxxsActionUser = null;

		try {
			yxxsActionUser = (YxxsActionUser)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = yxxsActionUser.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		YxxsActionUserModelImpl yxxsActionUserModelImpl = this;

		yxxsActionUserModelImpl._originalActionId = yxxsActionUserModelImpl._actionId;

		yxxsActionUserModelImpl._setOriginalActionId = false;

		yxxsActionUserModelImpl._originalUserId = yxxsActionUserModelImpl._userId;

		yxxsActionUserModelImpl._setOriginalUserId = false;

		yxxsActionUserModelImpl._originalOpenId = yxxsActionUserModelImpl._openId;
	}

	public HashMap toHash() {
		HashMap hash = new HashMap();

		hash.put("id", getId());
		hash.put("actionId", getActionId());
		hash.put("createId", getCreateId());
		hash.put("userId", getUserId());
		hash.put("userType", getUserType());
		hash.put("isLogged", getIsLogged());
		hash.put("openId", getOpenId());
		hash.put("createDate", getCreateDate());
		hash.put("loginDate", getLoginDate());
		hash.put("rName", getRName());
		hash.put("rMobile", getRMobile());
		hash.put("rSchool", getRSchool());

		return hash;
	}

	private long _id_;
	private long _actionId;
	private long _originalActionId;
	private boolean _setOriginalActionId;
	private long _createId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private int _userType;
	private int _isLogged;
	private String _openId;
	private String _originalOpenId;
	private Date _createDate;
	private Date _loginDate;
	private String _rName;
	private String _rMobile;
	private String _rSchool;
}