/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.model.impl;

import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringPool;

import com.yxxs.common.service.BaseModelImpl;

import com.yxxs.model.YxxsActionDealLog;
import com.yxxs.model.YxxsActionDealLogModel;

import org.codehaus.jackson.annotate.JsonIgnore;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;

/**
 * The base model implementation for the YxxsActionDealLog service. Represents a row in the &quot;yxxs_action_deal_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.yxxs.model.YxxsActionDealLogModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YxxsActionDealLogImpl}.
 * </p>
 *
 * @author Administrator
 * @see YxxsActionDealLogImpl
 * @see com.yxxs.model.YxxsActionDealLog
 * @see com.yxxs.model.YxxsActionDealLogModel
 * @generated
 */
@JSON(strict = true)
public class YxxsActionDealLogModelImpl extends BaseModelImpl<YxxsActionDealLog>
	implements YxxsActionDealLogModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a yxxs action deal log model instance should use the {@link com.yxxs.model.YxxsActionDealLog} interface instead.
	 */
	public static final String TABLE_NAME = "yxxs_action_deal_log";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "actionId", Types.BIGINT },
			{ "createId", Types.BIGINT },
			{ "type_", Types.INTEGER },
			{ "content", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP }
		};
	public static final String ORDER_BY_JPQL = " ORDER BY yxxsActionDealLog.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY yxxs_action_deal_log.createDate DESC";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.entity.cache.enabled.com.yxxs.model.YxxsActionDealLog"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.finder.cache.enabled.com.yxxs.model.YxxsActionDealLog"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.column.bitmask.enabled.com.yxxs.model.YxxsActionDealLog"),
			true);
	public static long ACTIONID_COLUMN_BITMASK = 1L;
	public static long CREATEID_COLUMN_BITMASK = 2L;

	public YxxsActionDealLogModelImpl() {
	}

	public long getPrimaryKey() {
		return _id_;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@JsonIgnore
	public Serializable getPrimaryKeyObj() {
		return new Long(_id_);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@JsonIgnore
	public Class<?> getModelClass() {
		return YxxsActionDealLog.class;
	}

	@JsonIgnore
	public String getModelClassName() {
		return YxxsActionDealLog.class.getName();
	}

	@JSON
	public long getId() {
		return _id_;
	}

	public void setId(long id) {
		this._id_ = id;
	}

	@JSON
	public long getActionId() {
		return _actionId;
	}

	public void setActionId(long actionId) {
		if (!_setOriginalActionId) {
			_setOriginalActionId = true;

			_originalActionId = _actionId;
		}

		this._actionId = actionId;
	}

	@JsonIgnore
	public long getOriginalActionId() {
		return _originalActionId;
	}

	@JSON
	public long getCreateId() {
		return _createId;
	}

	public void setCreateId(long createId) {
		if (!_setOriginalCreateId) {
			_setOriginalCreateId = true;

			_originalCreateId = _createId;
		}

		this._createId = createId;
	}

	@JsonIgnore
	public long getOriginalCreateId() {
		return _originalCreateId;
	}

	@JSON
	public int getType() {
		return _type_;
	}

	public void setType(int type) {
		this._type_ = type;
	}

	@JSON
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public void setContent(String content) {
		this._content = content;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		this._createDate = createDate;
	}

	@JsonIgnore
	public long getColumnBitmask() {
		return 0L;
	}

	@Override
	public YxxsActionDealLog toEscapedModel() {
		return null;
	}

	@Override
	public Object clone() {
		YxxsActionDealLogImpl yxxsActionDealLogImpl = new YxxsActionDealLogImpl();

		yxxsActionDealLogImpl.setId(getId());
		yxxsActionDealLogImpl.setActionId(getActionId());
		yxxsActionDealLogImpl.setCreateId(getCreateId());
		yxxsActionDealLogImpl.setType(getType());
		yxxsActionDealLogImpl.setContent(getContent());
		yxxsActionDealLogImpl.setCreateDate(getCreateDate());

		yxxsActionDealLogImpl.resetOriginalValues();

		return yxxsActionDealLogImpl;
	}

	public int compareTo(YxxsActionDealLog yxxsActionDealLog) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(),
				yxxsActionDealLog.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		YxxsActionDealLog yxxsActionDealLog = null;

		try {
			yxxsActionDealLog = (YxxsActionDealLog)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = yxxsActionDealLog.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		YxxsActionDealLogModelImpl yxxsActionDealLogModelImpl = this;

		yxxsActionDealLogModelImpl._originalActionId = yxxsActionDealLogModelImpl._actionId;

		yxxsActionDealLogModelImpl._setOriginalActionId = false;

		yxxsActionDealLogModelImpl._originalCreateId = yxxsActionDealLogModelImpl._createId;

		yxxsActionDealLogModelImpl._setOriginalCreateId = false;
	}

	public HashMap toHash() {
		HashMap hash = new HashMap();

		hash.put("id", getId());
		hash.put("actionId", getActionId());
		hash.put("createId", getCreateId());
		hash.put("type", getType());
		hash.put("content", getContent());
		hash.put("createDate", getCreateDate());

		return hash;
	}

	private long _id_;
	private long _actionId;
	private long _originalActionId;
	private boolean _setOriginalActionId;
	private long _createId;
	private long _originalCreateId;
	private boolean _setOriginalCreateId;
	private int _type_;
	private String _content;
	private Date _createDate;
}