/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.model.impl;

import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringPool;

import com.yxxs.common.service.BaseModelImpl;

import com.yxxs.model.YxxsAction;
import com.yxxs.model.YxxsActionModel;

import org.codehaus.jackson.annotate.JsonIgnore;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;

/**
 * The base model implementation for the YxxsAction service. Represents a row in the &quot;yxxs_action&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.yxxs.model.YxxsActionModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link YxxsActionImpl}.
 * </p>
 *
 * @author Administrator
 * @see YxxsActionImpl
 * @see com.yxxs.model.YxxsAction
 * @see com.yxxs.model.YxxsActionModel
 * @generated
 */
@JSON(strict = true)
public class YxxsActionModelImpl extends BaseModelImpl<YxxsAction>
	implements YxxsActionModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a yxxs action model instance should use the {@link com.yxxs.model.YxxsAction} interface instead.
	 */
	public static final String TABLE_NAME = "yxxs_action";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "appKey", Types.VARCHAR },
			{ "createId", Types.BIGINT },
			{ "flag", Types.INTEGER },
			{ "title", Types.VARCHAR },
			{ "describe_", Types.VARCHAR },
			{ "content", Types.VARCHAR },
			{ "url", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "endDate", Types.TIMESTAMP },
			{ "startDate", Types.TIMESTAMP }
		};
	public static final String ORDER_BY_JPQL = " ORDER BY yxxsAction.createDate DESC";
	public static final String ORDER_BY_SQL = " ORDER BY yxxs_action.createDate DESC";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.entity.cache.enabled.com.yxxs.model.YxxsAction"),
			false);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.finder.cache.enabled.com.yxxs.model.YxxsAction"),
			false);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.yxxs.common.util.BaseServicePropsUtil.get(
				"value.object.column.bitmask.enabled.com.yxxs.model.YxxsAction"),
			true);
	public static long APPKEY_COLUMN_BITMASK = 1L;

	public YxxsActionModelImpl() {
	}

	public long getPrimaryKey() {
		return _id_;
	}

	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@JsonIgnore
	public Serializable getPrimaryKeyObj() {
		return new Long(_id_);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@JsonIgnore
	public Class<?> getModelClass() {
		return YxxsAction.class;
	}

	@JsonIgnore
	public String getModelClassName() {
		return YxxsAction.class.getName();
	}

	@JSON
	public long getId() {
		return _id_;
	}

	public void setId(long id) {
		this._id_ = id;
	}

	@JSON
	public String getAppKey() {
		if (_appKey == null) {
			return StringPool.BLANK;
		}
		else {
			return _appKey;
		}
	}

	public void setAppKey(String appKey) {
		if (_originalAppKey == null) {
			_originalAppKey = _appKey;
		}

		this._appKey = appKey;
	}

	@JsonIgnore
	public String getOriginalAppKey() {
		return GetterUtil.getString(_originalAppKey);
	}

	@JSON
	public long getCreateId() {
		return _createId;
	}

	public void setCreateId(long createId) {
		this._createId = createId;
	}

	@JSON
	public int getFlag() {
		return _flag;
	}

	public void setFlag(int flag) {
		this._flag = flag;
	}

	@JSON
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	public void setTitle(String title) {
		this._title = title;
	}

	@JSON
	public String getDescribe_() {
		if (_describe_ == null) {
			return StringPool.BLANK;
		}
		else {
			return _describe_;
		}
	}

	public void setDescribe_(String describe_) {
		this._describe_ = describe_;
	}

	@JSON
	public String getContent() {
		if (_content == null) {
			return StringPool.BLANK;
		}
		else {
			return _content;
		}
	}

	public void setContent(String content) {
		this._content = content;
	}

	@JSON
	public String getUrl() {
		if (_url == null) {
			return StringPool.BLANK;
		}
		else {
			return _url;
		}
	}

	public void setUrl(String url) {
		this._url = url;
	}

	@JSON
	public Date getCreateDate() {
		return _createDate;
	}

	public void setCreateDate(Date createDate) {
		this._createDate = createDate;
	}

	@JSON
	public Date getEndDate() {
		return _endDate;
	}

	public void setEndDate(Date endDate) {
		this._endDate = endDate;
	}

	@JSON
	public Date getStartDate() {
		return _startDate;
	}

	public void setStartDate(Date startDate) {
		this._startDate = startDate;
	}

	@JsonIgnore
	public long getColumnBitmask() {
		return 0L;
	}

	@Override
	public YxxsAction toEscapedModel() {
		return null;
	}

	@Override
	public Object clone() {
		YxxsActionImpl yxxsActionImpl = new YxxsActionImpl();

		yxxsActionImpl.setId(getId());
		yxxsActionImpl.setAppKey(getAppKey());
		yxxsActionImpl.setCreateId(getCreateId());
		yxxsActionImpl.setFlag(getFlag());
		yxxsActionImpl.setTitle(getTitle());
		yxxsActionImpl.setDescribe_(getDescribe_());
		yxxsActionImpl.setContent(getContent());
		yxxsActionImpl.setUrl(getUrl());
		yxxsActionImpl.setCreateDate(getCreateDate());
		yxxsActionImpl.setEndDate(getEndDate());
		yxxsActionImpl.setStartDate(getStartDate());

		yxxsActionImpl.resetOriginalValues();

		return yxxsActionImpl;
	}

	public int compareTo(YxxsAction yxxsAction) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), yxxsAction.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		YxxsAction yxxsAction = null;

		try {
			yxxsAction = (YxxsAction)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = yxxsAction.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		YxxsActionModelImpl yxxsActionModelImpl = this;

		yxxsActionModelImpl._originalAppKey = yxxsActionModelImpl._appKey;
	}

	public HashMap toHash() {
		HashMap hash = new HashMap();

		hash.put("id", getId());
		hash.put("appKey", getAppKey());
		hash.put("createId", getCreateId());
		hash.put("flag", getFlag());
		hash.put("title", getTitle());
		hash.put("describe_", getDescribe_());
		hash.put("content", getContent());
		hash.put("url", getUrl());
		hash.put("createDate", getCreateDate());
		hash.put("endDate", getEndDate());
		hash.put("startDate", getStartDate());

		return hash;
	}

	private long _id_;
	private String _appKey;
	private String _originalAppKey;
	private long _createId;
	private int _flag;
	private String _title;
	private String _describe_;
	private String _content;
	private String _url;
	private Date _createDate;
	private Date _endDate;
	private Date _startDate;
}