/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.model;

import com.liferay.portal.kernel.bean.AutoEscape;

import com.yxxs.common.service.BaseModel;

import java.util.Date;

/**
 * The base model interface for the YxxsAction service. Represents a row in the &quot;yxxs_action&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.yxxs.model.impl.YxxsActionModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.yxxs.model.impl.YxxsActionImpl}.
 * </p>
 *
 * @author Administrator
 * @see YxxsAction
 * @see com.yxxs.model.impl.YxxsActionImpl
 * @see com.yxxs.model.impl.YxxsActionModelImpl
 * @generated
 */
public interface YxxsActionModel extends BaseModel<YxxsAction> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yxxs action model instance should use the {@link YxxsAction} interface instead.
	 */

	/**
	 * Returns the primary key of this yxxs action.
	 *
	 * @return the primary key of this yxxs action
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yxxs action.
	 *
	 * @param primaryKey the primary key of this yxxs action
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this yxxs action.
	 *
	 * @return the ID of this yxxs action
	 */
	public long getId();

	/**
	 * Sets the ID of this yxxs action.
	 *
	 * @param id the ID of this yxxs action
	 */
	public void setId(long id);

	/**
	 * Returns the app key of this yxxs action.
	 *
	 * @return the app key of this yxxs action
	 */
	@AutoEscape
	public String getAppKey();

	/**
	 * Sets the app key of this yxxs action.
	 *
	 * @param appKey the app key of this yxxs action
	 */
	public void setAppKey(String appKey);

	/**
	 * Returns the create ID of this yxxs action.
	 *
	 * @return the create ID of this yxxs action
	 */
	public long getCreateId();

	/**
	 * Sets the create ID of this yxxs action.
	 *
	 * @param createId the create ID of this yxxs action
	 */
	public void setCreateId(long createId);

	/**
	 * Returns the flag of this yxxs action.
	 *
	 * @return the flag of this yxxs action
	 */
	public int getFlag();

	/**
	 * Sets the flag of this yxxs action.
	 *
	 * @param flag the flag of this yxxs action
	 */
	public void setFlag(int flag);

	/**
	 * Returns the title of this yxxs action.
	 *
	 * @return the title of this yxxs action
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this yxxs action.
	 *
	 * @param title the title of this yxxs action
	 */
	public void setTitle(String title);

	/**
	 * Returns the describe_ of this yxxs action.
	 *
	 * @return the describe_ of this yxxs action
	 */
	@AutoEscape
	public String getDescribe_();

	/**
	 * Sets the describe_ of this yxxs action.
	 *
	 * @param describe_ the describe_ of this yxxs action
	 */
	public void setDescribe_(String describe_);

	/**
	 * Returns the content of this yxxs action.
	 *
	 * @return the content of this yxxs action
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this yxxs action.
	 *
	 * @param content the content of this yxxs action
	 */
	public void setContent(String content);

	/**
	 * Returns the url of this yxxs action.
	 *
	 * @return the url of this yxxs action
	 */
	@AutoEscape
	public String getUrl();

	/**
	 * Sets the url of this yxxs action.
	 *
	 * @param url the url of this yxxs action
	 */
	public void setUrl(String url);

	/**
	 * Returns the create date of this yxxs action.
	 *
	 * @return the create date of this yxxs action
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this yxxs action.
	 *
	 * @param createDate the create date of this yxxs action
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the end date of this yxxs action.
	 *
	 * @return the end date of this yxxs action
	 */
	public Date getEndDate();

	/**
	 * Sets the end date of this yxxs action.
	 *
	 * @param endDate the end date of this yxxs action
	 */
	public void setEndDate(Date endDate);

	/**
	 * Returns the start date of this yxxs action.
	 *
	 * @return the start date of this yxxs action
	 */
	public Date getStartDate();

	/**
	 * Sets the start date of this yxxs action.
	 *
	 * @param startDate the start date of this yxxs action
	 */
	public void setStartDate(Date startDate);

	public int hashCode();

	public String toString();
}