/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.model;

import com.liferay.portal.kernel.bean.AutoEscape;

import com.yxxs.common.service.BaseModel;

import java.util.Date;

/**
 * The base model interface for the YxxsWechatWall service. Represents a row in the &quot;yxxs_wechat_wall&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.yxxs.model.impl.YxxsWechatWallModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.yxxs.model.impl.YxxsWechatWallImpl}.
 * </p>
 *
 * @author Administrator
 * @see YxxsWechatWall
 * @see com.yxxs.model.impl.YxxsWechatWallImpl
 * @see com.yxxs.model.impl.YxxsWechatWallModelImpl
 * @generated
 */
public interface YxxsWechatWallModel extends BaseModel<YxxsWechatWall> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yxxs wechat wall model instance should use the {@link YxxsWechatWall} interface instead.
	 */

	/**
	 * Returns the primary key of this yxxs wechat wall.
	 *
	 * @return the primary key of this yxxs wechat wall
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yxxs wechat wall.
	 *
	 * @param primaryKey the primary key of this yxxs wechat wall
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this yxxs wechat wall.
	 *
	 * @return the ID of this yxxs wechat wall
	 */
	public long getId();

	/**
	 * Sets the ID of this yxxs wechat wall.
	 *
	 * @param id the ID of this yxxs wechat wall
	 */
	public void setId(long id);

	/**
	 * Returns the action ID of this yxxs wechat wall.
	 *
	 * @return the action ID of this yxxs wechat wall
	 */
	public long getActionId();

	/**
	 * Sets the action ID of this yxxs wechat wall.
	 *
	 * @param actionId the action ID of this yxxs wechat wall
	 */
	public void setActionId(long actionId);

	/**
	 * Returns the user ID of this yxxs wechat wall.
	 *
	 * @return the user ID of this yxxs wechat wall
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this yxxs wechat wall.
	 *
	 * @param userId the user ID of this yxxs wechat wall
	 */
	public void setUserId(long userId);

	/**
	 * Returns the show flag of this yxxs wechat wall.
	 *
	 * @return the show flag of this yxxs wechat wall
	 */
	public int getShowFlag();

	/**
	 * Sets the show flag of this yxxs wechat wall.
	 *
	 * @param showFlag the show flag of this yxxs wechat wall
	 */
	public void setShowFlag(int showFlag);

	/**
	 * Returns the content of this yxxs wechat wall.
	 *
	 * @return the content of this yxxs wechat wall
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this yxxs wechat wall.
	 *
	 * @param content the content of this yxxs wechat wall
	 */
	public void setContent(String content);

	/**
	 * Returns the open ID of this yxxs wechat wall.
	 *
	 * @return the open ID of this yxxs wechat wall
	 */
	@AutoEscape
	public String getOpenId();

	/**
	 * Sets the open ID of this yxxs wechat wall.
	 *
	 * @param openId the open ID of this yxxs wechat wall
	 */
	public void setOpenId(String openId);

	/**
	 * Returns the app key of this yxxs wechat wall.
	 *
	 * @return the app key of this yxxs wechat wall
	 */
	@AutoEscape
	public String getAppKey();

	/**
	 * Sets the app key of this yxxs wechat wall.
	 *
	 * @param appKey the app key of this yxxs wechat wall
	 */
	public void setAppKey(String appKey);

	/**
	 * Returns the create date of this yxxs wechat wall.
	 *
	 * @return the create date of this yxxs wechat wall
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this yxxs wechat wall.
	 *
	 * @param createDate the create date of this yxxs wechat wall
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the msg type of this yxxs wechat wall.
	 *
	 * @return the msg type of this yxxs wechat wall
	 */
	public int getMsgType();

	/**
	 * Sets the msg type of this yxxs wechat wall.
	 *
	 * @param msgType the msg type of this yxxs wechat wall
	 */
	public void setMsgType(int msgType);

	/**
	 * Returns the to ID of this yxxs wechat wall.
	 *
	 * @return the to ID of this yxxs wechat wall
	 */
	public long getToId();

	/**
	 * Sets the to ID of this yxxs wechat wall.
	 *
	 * @param toId the to ID of this yxxs wechat wall
	 */
	public void setToId(long toId);

	/**
	 * Returns the content type of this yxxs wechat wall.
	 *
	 * @return the content type of this yxxs wechat wall
	 */
	public int getContentType();

	/**
	 * Sets the content type of this yxxs wechat wall.
	 *
	 * @param contentType the content type of this yxxs wechat wall
	 */
	public void setContentType(int contentType);

	public int hashCode();

	public String toString();
}