/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.model;

import com.liferay.portal.kernel.bean.AutoEscape;

import com.yxxs.common.service.BaseModel;

import java.util.Date;

/**
 * The base model interface for the YxxsActionUser service. Represents a row in the &quot;yxxs_action_user&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.yxxs.model.impl.YxxsActionUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.yxxs.model.impl.YxxsActionUserImpl}.
 * </p>
 *
 * @author Administrator
 * @see YxxsActionUser
 * @see com.yxxs.model.impl.YxxsActionUserImpl
 * @see com.yxxs.model.impl.YxxsActionUserModelImpl
 * @generated
 */
public interface YxxsActionUserModel extends BaseModel<YxxsActionUser> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yxxs action user model instance should use the {@link YxxsActionUser} interface instead.
	 */

	/**
	 * Returns the primary key of this yxxs action user.
	 *
	 * @return the primary key of this yxxs action user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yxxs action user.
	 *
	 * @param primaryKey the primary key of this yxxs action user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this yxxs action user.
	 *
	 * @return the ID of this yxxs action user
	 */
	public long getId();

	/**
	 * Sets the ID of this yxxs action user.
	 *
	 * @param id the ID of this yxxs action user
	 */
	public void setId(long id);

	/**
	 * Returns the action ID of this yxxs action user.
	 *
	 * @return the action ID of this yxxs action user
	 */
	public long getActionId();

	/**
	 * Sets the action ID of this yxxs action user.
	 *
	 * @param actionId the action ID of this yxxs action user
	 */
	public void setActionId(long actionId);

	/**
	 * Returns the create ID of this yxxs action user.
	 *
	 * @return the create ID of this yxxs action user
	 */
	public long getCreateId();

	/**
	 * Sets the create ID of this yxxs action user.
	 *
	 * @param createId the create ID of this yxxs action user
	 */
	public void setCreateId(long createId);

	/**
	 * Returns the user ID of this yxxs action user.
	 *
	 * @return the user ID of this yxxs action user
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this yxxs action user.
	 *
	 * @param userId the user ID of this yxxs action user
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user type of this yxxs action user.
	 *
	 * @return the user type of this yxxs action user
	 */
	public int getUserType();

	/**
	 * Sets the user type of this yxxs action user.
	 *
	 * @param userType the user type of this yxxs action user
	 */
	public void setUserType(int userType);

	/**
	 * Returns the is logged of this yxxs action user.
	 *
	 * @return the is logged of this yxxs action user
	 */
	public int getIsLogged();

	/**
	 * Sets the is logged of this yxxs action user.
	 *
	 * @param isLogged the is logged of this yxxs action user
	 */
	public void setIsLogged(int isLogged);

	/**
	 * Returns the open ID of this yxxs action user.
	 *
	 * @return the open ID of this yxxs action user
	 */
	@AutoEscape
	public String getOpenId();

	/**
	 * Sets the open ID of this yxxs action user.
	 *
	 * @param openId the open ID of this yxxs action user
	 */
	public void setOpenId(String openId);

	/**
	 * Returns the create date of this yxxs action user.
	 *
	 * @return the create date of this yxxs action user
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this yxxs action user.
	 *
	 * @param createDate the create date of this yxxs action user
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the login date of this yxxs action user.
	 *
	 * @return the login date of this yxxs action user
	 */
	public Date getLoginDate();

	/**
	 * Sets the login date of this yxxs action user.
	 *
	 * @param loginDate the login date of this yxxs action user
	 */
	public void setLoginDate(Date loginDate);

	/**
	 * Returns the r name of this yxxs action user.
	 *
	 * @return the r name of this yxxs action user
	 */
	@AutoEscape
	public String getRName();

	/**
	 * Sets the r name of this yxxs action user.
	 *
	 * @param rName the r name of this yxxs action user
	 */
	public void setRName(String rName);

	/**
	 * Returns the r mobile of this yxxs action user.
	 *
	 * @return the r mobile of this yxxs action user
	 */
	@AutoEscape
	public String getRMobile();

	/**
	 * Sets the r mobile of this yxxs action user.
	 *
	 * @param rMobile the r mobile of this yxxs action user
	 */
	public void setRMobile(String rMobile);

	/**
	 * Returns the r school of this yxxs action user.
	 *
	 * @return the r school of this yxxs action user
	 */
	@AutoEscape
	public String getRSchool();

	/**
	 * Sets the r school of this yxxs action user.
	 *
	 * @param rSchool the r school of this yxxs action user
	 */
	public void setRSchool(String rSchool);

	public int hashCode();

	public String toString();
}