/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.model;

import com.liferay.portal.kernel.bean.AutoEscape;

import com.yxxs.common.service.BaseModel;

import java.util.Date;

/**
 * The base model interface for the YxxsActionDealLog service. Represents a row in the &quot;yxxs_action_deal_log&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.yxxs.model.impl.YxxsActionDealLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.yxxs.model.impl.YxxsActionDealLogImpl}.
 * </p>
 *
 * @author Administrator
 * @see YxxsActionDealLog
 * @see com.yxxs.model.impl.YxxsActionDealLogImpl
 * @see com.yxxs.model.impl.YxxsActionDealLogModelImpl
 * @generated
 */
public interface YxxsActionDealLogModel extends BaseModel<YxxsActionDealLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a yxxs action deal log model instance should use the {@link YxxsActionDealLog} interface instead.
	 */

	/**
	 * Returns the primary key of this yxxs action deal log.
	 *
	 * @return the primary key of this yxxs action deal log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this yxxs action deal log.
	 *
	 * @param primaryKey the primary key of this yxxs action deal log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this yxxs action deal log.
	 *
	 * @return the ID of this yxxs action deal log
	 */
	public long getId();

	/**
	 * Sets the ID of this yxxs action deal log.
	 *
	 * @param id the ID of this yxxs action deal log
	 */
	public void setId(long id);

	/**
	 * Returns the action ID of this yxxs action deal log.
	 *
	 * @return the action ID of this yxxs action deal log
	 */
	public long getActionId();

	/**
	 * Sets the action ID of this yxxs action deal log.
	 *
	 * @param actionId the action ID of this yxxs action deal log
	 */
	public void setActionId(long actionId);

	/**
	 * Returns the create ID of this yxxs action deal log.
	 *
	 * @return the create ID of this yxxs action deal log
	 */
	public long getCreateId();

	/**
	 * Sets the create ID of this yxxs action deal log.
	 *
	 * @param createId the create ID of this yxxs action deal log
	 */
	public void setCreateId(long createId);

	/**
	 * Returns the type of this yxxs action deal log.
	 *
	 * @return the type of this yxxs action deal log
	 */
	public int getType();

	/**
	 * Sets the type of this yxxs action deal log.
	 *
	 * @param type the type of this yxxs action deal log
	 */
	public void setType(int type);

	/**
	 * Returns the content of this yxxs action deal log.
	 *
	 * @return the content of this yxxs action deal log
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this yxxs action deal log.
	 *
	 * @param content the content of this yxxs action deal log
	 */
	public void setContent(String content);

	/**
	 * Returns the create date of this yxxs action deal log.
	 *
	 * @return the create date of this yxxs action deal log
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this yxxs action deal log.
	 *
	 * @param createDate the create date of this yxxs action deal log
	 */
	public void setCreateDate(Date createDate);

	public int hashCode();

	public String toString();
}