/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation; either version
 * 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 */

package com.yxxs.service.base;

import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;

import com.yxxs.model.GroupPrivilegeEntity;

import com.yxxs.service.GroupPrivilegeEntityLocalService;
import com.yxxs.service.persistence.GroupEntityPersistence;
import com.yxxs.service.persistence.GroupEntityPersistenceImpl;
import com.yxxs.service.persistence.GroupPrivilegeEntityPersistence;
import com.yxxs.service.persistence.GroupPrivilegeEntityPersistenceImpl;
import com.yxxs.service.persistence.PrivilegeItemEntityPersistence;
import com.yxxs.service.persistence.PrivilegeItemEntityPersistenceImpl;
import com.yxxs.service.persistence.UserGroupEntityPersistence;
import com.yxxs.service.persistence.UserGroupEntityPersistenceImpl;
import com.yxxs.service.persistence.UserPrivilegeEntityPersistence;
import com.yxxs.service.persistence.UserPrivilegeEntityPersistenceImpl;

import java.util.List;

/**
 * The base implementation of the group privilege entity local service.
 * 
 * <p>
 * This implementation exists only as a container for the default service methods generated by
 * ServiceBuilder. All custom service methods should be put in
 * {@link com.yxxs.service.impl.GroupPrivilegeEntityLocalServiceImpl}.
 * </p>
 * 
 * @author Administrator
 * @see com.yxxs.service.impl.GroupPrivilegeEntityLocalServiceImpl
 * @see com.yxxs.service.GroupPrivilegeEntityLocalServiceUtil
 * @generated
 */
public abstract class GroupPrivilegeEntityLocalServiceBaseImpl
    implements
      GroupPrivilegeEntityLocalService {
  /*
   * NOTE FOR DEVELOPERS:
   * 
   * Never modify or reference this class directly. Always use {@link
   * com.yxxs.service.GroupPrivilegeEntityLocalServiceUtil} to access the group privilege entity
   * local service.
   */

  /**
   * Adds the group privilege entity to the database. Also notifies the appropriate model listeners.
   * 
   * @param groupPrivilegeEntity the group privilege entity
   * @return the group privilege entity that was added
   * @throws SystemException if a system exception occurred
   */
  public GroupPrivilegeEntity addGroupPrivilegeEntity(GroupPrivilegeEntity groupPrivilegeEntity)
      throws SystemException {
    groupPrivilegeEntity.setNew(true);

    groupPrivilegeEntity = groupPrivilegeEntityPersistence.update(groupPrivilegeEntity);

    return groupPrivilegeEntity;
  }

  /**
   * Creates a new group privilege entity with the primary key. Does not add the group privilege
   * entity to the database.
   * 
   * @param id the primary key for the new group privilege entity
   * @return the new group privilege entity
   */
  public GroupPrivilegeEntity createGroupPrivilegeEntity(long id) {
    return groupPrivilegeEntityPersistence.create(id);
  }

  /**
   * Deletes the group privilege entity with the primary key from the database. Also notifies the
   * appropriate model listeners.
   * 
   * @param id the primary key of the group privilege entity
   * @throws PortalException if a group privilege entity with the primary key could not be found
   * @throws SystemException if a system exception occurred
   */
  public void deleteGroupPrivilegeEntity(long id) throws PortalException, SystemException {
    GroupPrivilegeEntity groupPrivilegeEntity = groupPrivilegeEntityPersistence.remove(id);
  }

  /**
   * Deletes the group privilege entity from the database. Also notifies the appropriate model
   * listeners.
   * 
   * @param groupPrivilegeEntity the group privilege entity
   * @throws SystemException if a system exception occurred
   */
  public void deleteGroupPrivilegeEntity(GroupPrivilegeEntity groupPrivilegeEntity)
      throws SystemException {
    groupPrivilegeEntityPersistence.remove(groupPrivilegeEntity);
  }

  public GroupPrivilegeEntity fetchGroupPrivilegeEntity(long id) throws SystemException {
    return groupPrivilegeEntityPersistence.fetchByPrimaryKey(id);
  }

  /**
   * Returns the group privilege entity with the primary key.
   * 
   * @param id the primary key of the group privilege entity
   * @return the group privilege entity
   * @throws PortalException if a group privilege entity with the primary key could not be found
   * @throws SystemException if a system exception occurred
   */
  public GroupPrivilegeEntity getGroupPrivilegeEntity(long id) throws PortalException,
      SystemException {
    return groupPrivilegeEntityPersistence.findByPrimaryKey(id);
  }

  /**
   * Returns a range of all the group privilege entities.
   * 
   * <p>
   * Useful when paginating results. Returns a maximum of <code>end - start</code> instances.
   * <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result
   * set. Thus, <code>0</code> refers to the first result in the set. Setting both
   * <code>start</code> and <code>end</code> to
   * {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
   * </p>
   * 
   * @param start the lower bound of the range of group privilege entities
   * @param end the upper bound of the range of group privilege entities (not inclusive)
   * @return the range of group privilege entities
   * @throws SystemException if a system exception occurred
   */
  public List<GroupPrivilegeEntity> getGroupPrivilegeEntities(int start, int end)
      throws SystemException {
    return groupPrivilegeEntityPersistence.findAll(start, end);
  }

  /**
   * Returns the number of group privilege entities.
   * 
   * @return the number of group privilege entities
   * @throws SystemException if a system exception occurred
   */
  public int getGroupPrivilegeEntitiesCount() throws SystemException {
    return groupPrivilegeEntityPersistence.countAll();
  }

  /**
   * Updates the group privilege entity in the database or adds it if it does not yet exist. Also
   * notifies the appropriate model listeners.
   * 
   * @param groupPrivilegeEntity the group privilege entity
   * @param merge whether to merge the group privilege entity with the current session. See
   *        {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)}
   *        for an explanation.
   * @return the group privilege entity that was updated
   * @throws SystemException if a system exception occurred
   */
  public GroupPrivilegeEntity updateGroupPrivilegeEntity(GroupPrivilegeEntity groupPrivilegeEntity)
      throws SystemException {
    groupPrivilegeEntity = groupPrivilegeEntityPersistence.update(groupPrivilegeEntity);

    return groupPrivilegeEntity;
  }

  /**
   * Returns the group entity persistence.
   * 
   * @return the group entity persistence
   */
  public GroupEntityPersistence getGroupEntityPersistence() {
    return groupEntityPersistence;
  }

  /**
   * Sets the group entity persistence.
   * 
   * @param groupEntityPersistence the group entity persistence
   */

  /**
   * Returns the group privilege entity persistence.
   * 
   * @return the group privilege entity persistence
   */
  public GroupPrivilegeEntityPersistence getGroupPrivilegeEntityPersistence() {
    return groupPrivilegeEntityPersistence;
  }

  /**
   * Sets the group privilege entity persistence.
   * 
   * @param groupPrivilegeEntityPersistence the group privilege entity persistence
   */

  /**
   * Returns the privilege item entity persistence.
   * 
   * @return the privilege item entity persistence
   */
  public PrivilegeItemEntityPersistence getPrivilegeItemEntityPersistence() {
    return privilegeItemEntityPersistence;
  }

  /**
   * Sets the privilege item entity persistence.
   * 
   * @param privilegeItemEntityPersistence the privilege item entity persistence
   */

  /**
   * Returns the user group entity persistence.
   * 
   * @return the user group entity persistence
   */
  public UserGroupEntityPersistence getUserGroupEntityPersistence() {
    return userGroupEntityPersistence;
  }

  /**
   * Sets the user group entity persistence.
   * 
   * @param userGroupEntityPersistence the user group entity persistence
   */

  /**
   * Returns the user privilege entity persistence.
   * 
   * @return the user privilege entity persistence
   */
  public UserPrivilegeEntityPersistence getUserPrivilegeEntityPersistence() {
    return userPrivilegeEntityPersistence;
  }

  /**
   * Sets the user privilege entity persistence.
   * 
   * @param userPrivilegeEntityPersistence the user privilege entity persistence
   */
  public void afterPropertiesSet() {}

  public void destroy() {}

  protected Class<?> getModelClass() {
    return GroupPrivilegeEntity.class;
  }

  protected String getModelClassName() {
    return GroupPrivilegeEntity.class.getName();
  }

  protected GroupEntityPersistence groupEntityPersistence = new GroupEntityPersistenceImpl();
  protected GroupPrivilegeEntityPersistence groupPrivilegeEntityPersistence =
      new GroupPrivilegeEntityPersistenceImpl();
  protected PrivilegeItemEntityPersistence privilegeItemEntityPersistence =
      new PrivilegeItemEntityPersistenceImpl();
  protected UserGroupEntityPersistence userGroupEntityPersistence =
      new UserGroupEntityPersistenceImpl();
  protected UserPrivilegeEntityPersistence userPrivilegeEntityPersistence =
      new UserPrivilegeEntityPersistenceImpl();
  private static Log _log = LogFactoryUtil.getLog(GroupPrivilegeEntityLocalServiceBaseImpl.class);
}
