/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation; either version
 * 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 */

package com.yxxs.service.base;

import com.yxxs.model.UserPrivilegeEntity;

import com.yxxs.service.UserPrivilegeEntityService;
import com.yxxs.service.persistence.GroupEntityPersistence;
import com.yxxs.service.persistence.GroupEntityPersistenceImpl;
import com.yxxs.service.persistence.GroupPrivilegeEntityPersistence;
import com.yxxs.service.persistence.GroupPrivilegeEntityPersistenceImpl;
import com.yxxs.service.persistence.PrivilegeItemEntityPersistence;
import com.yxxs.service.persistence.PrivilegeItemEntityPersistenceImpl;
import com.yxxs.service.persistence.UserGroupEntityPersistence;
import com.yxxs.service.persistence.UserGroupEntityPersistenceImpl;
import com.yxxs.service.persistence.UserPrivilegeEntityPersistence;
import com.yxxs.service.persistence.UserPrivilegeEntityPersistenceImpl;

/**
 * The base implementation of the user privilege entity remote service.
 * 
 * <p>
 * This implementation exists only as a container for the default service methods generated by
 * ServiceBuilder. All custom service methods should be put in
 * {@link com.yxxs.service.impl.UserPrivilegeEntityServiceImpl}.
 * </p>
 * 
 * @author Administrator
 * @see com.yxxs.service.impl.UserPrivilegeEntityServiceImpl
 * @see com.yxxs.service.UserPrivilegeEntityServiceUtil
 * @generated
 */
public abstract class UserPrivilegeEntityServiceBaseImpl implements UserPrivilegeEntityService {
  /*
   * NOTE FOR DEVELOPERS:
   * 
   * Never modify or reference this class directly. Always use {@link
   * com.yxxs.service.UserPrivilegeEntityServiceUtil} to access the user privilege entity remote
   * service.
   */

  /**
   * Returns the group entity persistence.
   * 
   * @return the group entity persistence
   */
  public GroupEntityPersistence getGroupEntityPersistence() {
    return groupEntityPersistence;
  }

  /**
   * Sets the group entity persistence.
   * 
   * @param groupEntityPersistence the group entity persistence
   */

  /**
   * Returns the group privilege entity persistence.
   * 
   * @return the group privilege entity persistence
   */
  public GroupPrivilegeEntityPersistence getGroupPrivilegeEntityPersistence() {
    return groupPrivilegeEntityPersistence;
  }

  /**
   * Sets the group privilege entity persistence.
   * 
   * @param groupPrivilegeEntityPersistence the group privilege entity persistence
   */

  /**
   * Returns the privilege item entity persistence.
   * 
   * @return the privilege item entity persistence
   */
  public PrivilegeItemEntityPersistence getPrivilegeItemEntityPersistence() {
    return privilegeItemEntityPersistence;
  }

  /**
   * Sets the privilege item entity persistence.
   * 
   * @param privilegeItemEntityPersistence the privilege item entity persistence
   */

  /**
   * Returns the user group entity persistence.
   * 
   * @return the user group entity persistence
   */
  public UserGroupEntityPersistence getUserGroupEntityPersistence() {
    return userGroupEntityPersistence;
  }

  /**
   * Sets the user group entity persistence.
   * 
   * @param userGroupEntityPersistence the user group entity persistence
   */

  /**
   * Returns the user privilege entity persistence.
   * 
   * @return the user privilege entity persistence
   */
  public UserPrivilegeEntityPersistence getUserPrivilegeEntityPersistence() {
    return userPrivilegeEntityPersistence;
  }

  /**
   * Sets the user privilege entity persistence.
   * 
   * @param userPrivilegeEntityPersistence the user privilege entity persistence
   */
  public void afterPropertiesSet() {}

  public void destroy() {}

  protected Class<?> getModelClass() {
    return UserPrivilegeEntity.class;
  }

  protected String getModelClassName() {
    return UserPrivilegeEntity.class.getName();
  }

  protected GroupEntityPersistence groupEntityPersistence = new GroupEntityPersistenceImpl();
  protected GroupPrivilegeEntityPersistence groupPrivilegeEntityPersistence =
      new GroupPrivilegeEntityPersistenceImpl();
  protected PrivilegeItemEntityPersistence privilegeItemEntityPersistence =
      new PrivilegeItemEntityPersistenceImpl();
  protected UserGroupEntityPersistence userGroupEntityPersistence =
      new UserGroupEntityPersistenceImpl();
  protected UserPrivilegeEntityPersistence userPrivilegeEntityPersistence =
      new UserPrivilegeEntityPersistenceImpl();
}
