/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 * 
 * This library is free software; you can redistribute it and/or modify it under the terms of the
 * GNU Lesser General Public License as published by the Free Software Foundation; either version
 * 2.1 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without
 * even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
 * Lesser General Public License for more details.
 */

package com.yxxs.service.base;

import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;

import com.yxxs.model.UserPrivilegeEntity;

import com.yxxs.service.UserPrivilegeEntityLocalService;
import com.yxxs.service.persistence.GroupEntityPersistence;
import com.yxxs.service.persistence.GroupEntityPersistenceImpl;
import com.yxxs.service.persistence.GroupPrivilegeEntityPersistence;
import com.yxxs.service.persistence.GroupPrivilegeEntityPersistenceImpl;
import com.yxxs.service.persistence.PrivilegeItemEntityPersistence;
import com.yxxs.service.persistence.PrivilegeItemEntityPersistenceImpl;
import com.yxxs.service.persistence.UserGroupEntityPersistence;
import com.yxxs.service.persistence.UserGroupEntityPersistenceImpl;
import com.yxxs.service.persistence.UserPrivilegeEntityPersistence;
import com.yxxs.service.persistence.UserPrivilegeEntityPersistenceImpl;

import java.util.List;

/**
 * The base implementation of the user privilege entity local service.
 * 
 * <p>
 * This implementation exists only as a container for the default service methods generated by
 * ServiceBuilder. All custom service methods should be put in
 * {@link com.yxxs.service.impl.UserPrivilegeEntityLocalServiceImpl}.
 * </p>
 * 
 * @author Administrator
 * @see com.yxxs.service.impl.UserPrivilegeEntityLocalServiceImpl
 * @see com.yxxs.service.UserPrivilegeEntityLocalServiceUtil
 * @generated
 */
public abstract class UserPrivilegeEntityLocalServiceBaseImpl
    implements
      UserPrivilegeEntityLocalService {
  /*
   * NOTE FOR DEVELOPERS:
   * 
   * Never modify or reference this class directly. Always use {@link
   * com.yxxs.service.UserPrivilegeEntityLocalServiceUtil} to access the user privilege entity local
   * service.
   */

  /**
   * Adds the user privilege entity to the database. Also notifies the appropriate model listeners.
   * 
   * @param userPrivilegeEntity the user privilege entity
   * @return the user privilege entity that was added
   * @throws SystemException if a system exception occurred
   */
  public UserPrivilegeEntity addUserPrivilegeEntity(UserPrivilegeEntity userPrivilegeEntity)
      throws SystemException {
    userPrivilegeEntity.setNew(true);

    userPrivilegeEntity = userPrivilegeEntityPersistence.update(userPrivilegeEntity);

    return userPrivilegeEntity;
  }

  /**
   * Creates a new user privilege entity with the primary key. Does not add the user privilege
   * entity to the database.
   * 
   * @param id the primary key for the new user privilege entity
   * @return the new user privilege entity
   */
  public UserPrivilegeEntity createUserPrivilegeEntity(long id) {
    return userPrivilegeEntityPersistence.create(id);
  }

  /**
   * Deletes the user privilege entity with the primary key from the database. Also notifies the
   * appropriate model listeners.
   * 
   * @param id the primary key of the user privilege entity
   * @throws PortalException if a user privilege entity with the primary key could not be found
   * @throws SystemException if a system exception occurred
   */
  public void deleteUserPrivilegeEntity(long id) throws PortalException, SystemException {
    UserPrivilegeEntity userPrivilegeEntity = userPrivilegeEntityPersistence.remove(id);
  }

  /**
   * Deletes the user privilege entity from the database. Also notifies the appropriate model
   * listeners.
   * 
   * @param userPrivilegeEntity the user privilege entity
   * @throws SystemException if a system exception occurred
   */
  public void deleteUserPrivilegeEntity(UserPrivilegeEntity userPrivilegeEntity)
      throws SystemException {
    userPrivilegeEntityPersistence.remove(userPrivilegeEntity);
  }

  public UserPrivilegeEntity fetchUserPrivilegeEntity(long id) throws SystemException {
    return userPrivilegeEntityPersistence.fetchByPrimaryKey(id);
  }

  /**
   * Returns the user privilege entity with the primary key.
   * 
   * @param id the primary key of the user privilege entity
   * @return the user privilege entity
   * @throws PortalException if a user privilege entity with the primary key could not be found
   * @throws SystemException if a system exception occurred
   */
  public UserPrivilegeEntity getUserPrivilegeEntity(long id) throws PortalException,
      SystemException {
    return userPrivilegeEntityPersistence.findByPrimaryKey(id);
  }

  /**
   * Returns a range of all the user privilege entities.
   * 
   * <p>
   * Useful when paginating results. Returns a maximum of <code>end - start</code> instances.
   * <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result
   * set. Thus, <code>0</code> refers to the first result in the set. Setting both
   * <code>start</code> and <code>end</code> to
   * {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
   * </p>
   * 
   * @param start the lower bound of the range of user privilege entities
   * @param end the upper bound of the range of user privilege entities (not inclusive)
   * @return the range of user privilege entities
   * @throws SystemException if a system exception occurred
   */
  public List<UserPrivilegeEntity> getUserPrivilegeEntities(int start, int end)
      throws SystemException {
    return userPrivilegeEntityPersistence.findAll(start, end);
  }

  /**
   * Returns the number of user privilege entities.
   * 
   * @return the number of user privilege entities
   * @throws SystemException if a system exception occurred
   */
  public int getUserPrivilegeEntitiesCount() throws SystemException {
    return userPrivilegeEntityPersistence.countAll();
  }

  /**
   * Updates the user privilege entity in the database or adds it if it does not yet exist. Also
   * notifies the appropriate model listeners.
   * 
   * @param userPrivilegeEntity the user privilege entity
   * @param merge whether to merge the user privilege entity with the current session. See
   *        {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)}
   *        for an explanation.
   * @return the user privilege entity that was updated
   * @throws SystemException if a system exception occurred
   */
  public UserPrivilegeEntity updateUserPrivilegeEntity(UserPrivilegeEntity userPrivilegeEntity)
      throws SystemException {
    userPrivilegeEntity = userPrivilegeEntityPersistence.update(userPrivilegeEntity);

    return userPrivilegeEntity;
  }

  /**
   * Returns the group entity persistence.
   * 
   * @return the group entity persistence
   */
  public GroupEntityPersistence getGroupEntityPersistence() {
    return groupEntityPersistence;
  }

  /**
   * Sets the group entity persistence.
   * 
   * @param groupEntityPersistence the group entity persistence
   */

  /**
   * Returns the group privilege entity persistence.
   * 
   * @return the group privilege entity persistence
   */
  public GroupPrivilegeEntityPersistence getGroupPrivilegeEntityPersistence() {
    return groupPrivilegeEntityPersistence;
  }

  /**
   * Sets the group privilege entity persistence.
   * 
   * @param groupPrivilegeEntityPersistence the group privilege entity persistence
   */

  /**
   * Returns the privilege item entity persistence.
   * 
   * @return the privilege item entity persistence
   */
  public PrivilegeItemEntityPersistence getPrivilegeItemEntityPersistence() {
    return privilegeItemEntityPersistence;
  }

  /**
   * Sets the privilege item entity persistence.
   * 
   * @param privilegeItemEntityPersistence the privilege item entity persistence
   */

  /**
   * Returns the user group entity persistence.
   * 
   * @return the user group entity persistence
   */
  public UserGroupEntityPersistence getUserGroupEntityPersistence() {
    return userGroupEntityPersistence;
  }

  /**
   * Sets the user group entity persistence.
   * 
   * @param userGroupEntityPersistence the user group entity persistence
   */

  /**
   * Returns the user privilege entity persistence.
   * 
   * @return the user privilege entity persistence
   */
  public UserPrivilegeEntityPersistence getUserPrivilegeEntityPersistence() {
    return userPrivilegeEntityPersistence;
  }

  /**
   * Sets the user privilege entity persistence.
   * 
   * @param userPrivilegeEntityPersistence the user privilege entity persistence
   */
  public void afterPropertiesSet() {}

  public void destroy() {}

  protected Class<?> getModelClass() {
    return UserPrivilegeEntity.class;
  }

  protected String getModelClassName() {
    return UserPrivilegeEntity.class.getName();
  }

  protected GroupEntityPersistence groupEntityPersistence = new GroupEntityPersistenceImpl();
  protected GroupPrivilegeEntityPersistence groupPrivilegeEntityPersistence =
      new GroupPrivilegeEntityPersistenceImpl();
  protected PrivilegeItemEntityPersistence privilegeItemEntityPersistence =
      new PrivilegeItemEntityPersistenceImpl();
  protected UserGroupEntityPersistence userGroupEntityPersistence =
      new UserGroupEntityPersistenceImpl();
  protected UserPrivilegeEntityPersistence userPrivilegeEntityPersistence =
      new UserPrivilegeEntityPersistenceImpl();
  private static Log _log = LogFactoryUtil.getLog(UserPrivilegeEntityLocalServiceBaseImpl.class);
}
