/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.service.base;

import com.yxxs.model.YxxsActionDealLog;

import com.yxxs.service.YxxsActionDealLogService;
import com.yxxs.service.persistence.YxxsActionDealLogPersistence;
import com.yxxs.service.persistence.YxxsActionDealLogPersistenceImpl;
import com.yxxs.service.persistence.YxxsActionPersistence;
import com.yxxs.service.persistence.YxxsActionPersistenceImpl;
import com.yxxs.service.persistence.YxxsActionUserPersistence;
import com.yxxs.service.persistence.YxxsActionUserPersistenceImpl;
import com.yxxs.service.persistence.YxxsWechatWallPersistence;
import com.yxxs.service.persistence.YxxsWechatWallPersistenceImpl;

/**
 * The base implementation of the yxxs action deal log remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.yxxs.service.impl.YxxsActionDealLogServiceImpl}.
 * </p>
 *
 * @author Administrator
 * @see com.yxxs.service.impl.YxxsActionDealLogServiceImpl
 * @see com.yxxs.service.YxxsActionDealLogServiceUtil
 * @generated
 */
public abstract class YxxsActionDealLogServiceBaseImpl
	implements YxxsActionDealLogService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.yxxs.service.YxxsActionDealLogServiceUtil} to access the yxxs action deal log remote service.
	 */

	/**
	 * Returns the yxxs action persistence.
	 *
	 * @return the yxxs action persistence
	 */
	public YxxsActionPersistence getYxxsActionPersistence() {
		return yxxsActionPersistence;
	}

	/**
	 * Sets the yxxs action persistence.
	 *
	 * @param yxxsActionPersistence the yxxs action persistence
	 */

	/**
	 * Returns the yxxs action deal log persistence.
	 *
	 * @return the yxxs action deal log persistence
	 */
	public YxxsActionDealLogPersistence getYxxsActionDealLogPersistence() {
		return yxxsActionDealLogPersistence;
	}

	/**
	 * Sets the yxxs action deal log persistence.
	 *
	 * @param yxxsActionDealLogPersistence the yxxs action deal log persistence
	 */

	/**
	 * Returns the yxxs action user persistence.
	 *
	 * @return the yxxs action user persistence
	 */
	public YxxsActionUserPersistence getYxxsActionUserPersistence() {
		return yxxsActionUserPersistence;
	}

	/**
	 * Sets the yxxs action user persistence.
	 *
	 * @param yxxsActionUserPersistence the yxxs action user persistence
	 */

	/**
	 * Returns the yxxs wechat wall persistence.
	 *
	 * @return the yxxs wechat wall persistence
	 */
	public YxxsWechatWallPersistence getYxxsWechatWallPersistence() {
		return yxxsWechatWallPersistence;
	}

	/**
	 * Sets the yxxs wechat wall persistence.
	 *
	 * @param yxxsWechatWallPersistence the yxxs wechat wall persistence
	 */
	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	protected Class<?> getModelClass() {
		return YxxsActionDealLog.class;
	}

	protected String getModelClassName() {
		return YxxsActionDealLog.class.getName();
	}

	protected YxxsActionPersistence yxxsActionPersistence = new YxxsActionPersistenceImpl();
	protected YxxsActionDealLogPersistence yxxsActionDealLogPersistence = new YxxsActionDealLogPersistenceImpl();
	protected YxxsActionUserPersistence yxxsActionUserPersistence = new YxxsActionUserPersistenceImpl();
	protected YxxsWechatWallPersistence yxxsWechatWallPersistence = new YxxsWechatWallPersistenceImpl();
}