/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.yxxs.service.base;

import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;

import com.yxxs.model.YxxsWechatWall;

import com.yxxs.service.YxxsWechatWallLocalService;
import com.yxxs.service.persistence.YxxsActionDealLogPersistence;
import com.yxxs.service.persistence.YxxsActionDealLogPersistenceImpl;
import com.yxxs.service.persistence.YxxsActionPersistence;
import com.yxxs.service.persistence.YxxsActionPersistenceImpl;
import com.yxxs.service.persistence.YxxsActionUserPersistence;
import com.yxxs.service.persistence.YxxsActionUserPersistenceImpl;
import com.yxxs.service.persistence.YxxsWechatWallPersistence;
import com.yxxs.service.persistence.YxxsWechatWallPersistenceImpl;

import java.util.List;

/**
 * The base implementation of the yxxs wechat wall local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.yxxs.service.impl.YxxsWechatWallLocalServiceImpl}.
 * </p>
 *
 * @author Administrator
 * @see com.yxxs.service.impl.YxxsWechatWallLocalServiceImpl
 * @see com.yxxs.service.YxxsWechatWallLocalServiceUtil
 * @generated
 */
public abstract class YxxsWechatWallLocalServiceBaseImpl
	implements YxxsWechatWallLocalService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.yxxs.service.YxxsWechatWallLocalServiceUtil} to access the yxxs wechat wall local service.
	 */

	/**
	 * Adds the yxxs wechat wall to the database. Also notifies the appropriate model listeners.
	 *
	 * @param yxxsWechatWall the yxxs wechat wall
	 * @return the yxxs wechat wall that was added
	 * @throws SystemException if a system exception occurred
	 */
	public YxxsWechatWall addYxxsWechatWall(YxxsWechatWall yxxsWechatWall)
		throws SystemException {
		yxxsWechatWall.setNew(true);

		yxxsWechatWall = yxxsWechatWallPersistence.update(yxxsWechatWall);

		return yxxsWechatWall;
	}

	/**
	 * Creates a new yxxs wechat wall with the primary key. Does not add the yxxs wechat wall to the database.
	 *
	 * @param id the primary key for the new yxxs wechat wall
	 * @return the new yxxs wechat wall
	 */
	public YxxsWechatWall createYxxsWechatWall(long id) {
		return yxxsWechatWallPersistence.create(id);
	}

	/**
	 * Deletes the yxxs wechat wall with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the yxxs wechat wall
	 * @throws PortalException if a yxxs wechat wall with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteYxxsWechatWall(long id)
		throws PortalException, SystemException {
		YxxsWechatWall yxxsWechatWall = yxxsWechatWallPersistence.remove(id);
	}

	/**
	 * Deletes the yxxs wechat wall from the database. Also notifies the appropriate model listeners.
	 *
	 * @param yxxsWechatWall the yxxs wechat wall
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteYxxsWechatWall(YxxsWechatWall yxxsWechatWall)
		throws SystemException {
		yxxsWechatWallPersistence.remove(yxxsWechatWall);
	}

	public YxxsWechatWall fetchYxxsWechatWall(long id)
		throws SystemException {
		return yxxsWechatWallPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the yxxs wechat wall with the primary key.
	 *
	 * @param id the primary key of the yxxs wechat wall
	 * @return the yxxs wechat wall
	 * @throws PortalException if a yxxs wechat wall with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public YxxsWechatWall getYxxsWechatWall(long id)
		throws PortalException, SystemException {
		return yxxsWechatWallPersistence.findByPrimaryKey(id);
	}

	/**
	 * Returns a range of all the yxxs wechat walls.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of yxxs wechat walls
	 * @param end the upper bound of the range of yxxs wechat walls (not inclusive)
	 * @return the range of yxxs wechat walls
	 * @throws SystemException if a system exception occurred
	 */
	public List<YxxsWechatWall> getYxxsWechatWalls(int start, int end)
		throws SystemException {
		return yxxsWechatWallPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of yxxs wechat walls.
	 *
	 * @return the number of yxxs wechat walls
	 * @throws SystemException if a system exception occurred
	 */
	public int getYxxsWechatWallsCount() throws SystemException {
		return yxxsWechatWallPersistence.countAll();
	}

	/**
	 * Updates the yxxs wechat wall in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param yxxsWechatWall the yxxs wechat wall
	 * @param merge whether to merge the yxxs wechat wall with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the yxxs wechat wall that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public YxxsWechatWall updateYxxsWechatWall(YxxsWechatWall yxxsWechatWall)
		throws SystemException {
		yxxsWechatWall = yxxsWechatWallPersistence.update(yxxsWechatWall);

		return yxxsWechatWall;
	}

	/**
	 * Returns the yxxs action persistence.
	 *
	 * @return the yxxs action persistence
	 */
	public YxxsActionPersistence getYxxsActionPersistence() {
		return yxxsActionPersistence;
	}

	/**
	 * Sets the yxxs action persistence.
	 *
	 * @param yxxsActionPersistence the yxxs action persistence
	 */

	/**
	 * Returns the yxxs action deal log persistence.
	 *
	 * @return the yxxs action deal log persistence
	 */
	public YxxsActionDealLogPersistence getYxxsActionDealLogPersistence() {
		return yxxsActionDealLogPersistence;
	}

	/**
	 * Sets the yxxs action deal log persistence.
	 *
	 * @param yxxsActionDealLogPersistence the yxxs action deal log persistence
	 */

	/**
	 * Returns the yxxs action user persistence.
	 *
	 * @return the yxxs action user persistence
	 */
	public YxxsActionUserPersistence getYxxsActionUserPersistence() {
		return yxxsActionUserPersistence;
	}

	/**
	 * Sets the yxxs action user persistence.
	 *
	 * @param yxxsActionUserPersistence the yxxs action user persistence
	 */

	/**
	 * Returns the yxxs wechat wall persistence.
	 *
	 * @return the yxxs wechat wall persistence
	 */
	public YxxsWechatWallPersistence getYxxsWechatWallPersistence() {
		return yxxsWechatWallPersistence;
	}

	/**
	 * Sets the yxxs wechat wall persistence.
	 *
	 * @param yxxsWechatWallPersistence the yxxs wechat wall persistence
	 */
	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	protected Class<?> getModelClass() {
		return YxxsWechatWall.class;
	}

	protected String getModelClassName() {
		return YxxsWechatWall.class.getName();
	}

	protected YxxsActionPersistence yxxsActionPersistence = new YxxsActionPersistenceImpl();
	protected YxxsActionDealLogPersistence yxxsActionDealLogPersistence = new YxxsActionDealLogPersistenceImpl();
	protected YxxsActionUserPersistence yxxsActionUserPersistence = new YxxsActionUserPersistenceImpl();
	protected YxxsWechatWallPersistence yxxsWechatWallPersistence = new YxxsWechatWallPersistenceImpl();
	private static Log _log = LogFactoryUtil.getLog(YxxsWechatWallLocalServiceBaseImpl.class);
}